# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: QNO Notes
author: JSW
logo: logo_valley_SP.png
#exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: jbook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jhihsheng/jbook # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: JLW_icon.png
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
  announcement: "Hi, welcome!" # A banner announcement at the top of the site.
  google_analytics_id: G-RQB6TED6E8
sphinx:
    config:
        #html_theme: renku
        #html_theme: quantecon_book_theme
    extra_extensions:
      - sphinxcontrib.mermaid
      - sphinxcontrib.wavedrom
      - sphinx_proof
      - sphinx_exercise